### ISSUE TITLE
the bug existed in the vectorizer.py

### ISSUE THREAD

**Issue by dongrixinyu** [zveryansky/textvec#4]
the 35th line sp.spdiag(y == val ......) might be wrong.
i assume that u maybe wanna write sp.spdiag([i for i in y if i == val] ......)

expect your reply,thx!

**Comment by dongrixinyu** [comment]
another problem.
i wanna use the supervised method such as tfrf, tfchi2 etc. 
when i finished training set on these method and get the _tp, _fn, _tn, _fp attributes. later, i wanna  apply these attributes on the testing set, i have no inerface to get access to these attributes. so does sklearn.itidf.

so i rewrite your code and provide a method to store these info in file.  when i  wanna use this method to predict, i read attributes and feed into the model. so ,i expect to add this kind of method, much more convenient.

**Comment by dongrixinyu** [comment]
the 286th line in vectorizer.py is wrong.plz check it

**Comment by zveryansky** [comment]
@dongrixinyu Thanks for the feedback! It will be better to have a separate issues for different problems. Please, if you think that something is wrong, provide as much info as possible and feel free to create a PR fixing all of this and providing unit tests.
